name: CI tests

on: [push, pull_request]

jobs:

  Run-tests:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
      with:
        lfs: 'true'
        submodules: recursive

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install git git-lfs g++-6 colordiff coreutils graphviz inkscape make cmake
        sudo git lfs install

    - name: generate lfs file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: restore lfs cache
      uses: actions/cache@v2
      id: lfs-cache
      with:
        path: recursive
        key: recursive

    - name: pull lfs files
      uses: actions/checkout@v2
    - run: git lfs pull

    - name: Execute test script
      run: stdbuf -i0 -o0 -e0 ./.github/ci/test.sh
